query ($externalIds: [String!]) {
  allFactSheets(filter: {externalIds: $externalIds}) {
    edges {
      node {
        id
        type
        name
        ... on Provider {
          externalId {
            externalId
          }
        }
        ... on Process {
          externalId {
            externalId
          }
        }
        ... on Project {
          externalId {
            externalId
          }
        }
        ... on Application {
          externalId {
            externalId
          }
        }
        ... on DataObject {
          externalId {
            externalId
          }
        }
      }
    }
  }
}
