name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true

  build:
    name: Create cross-platform release builds, tag and upload binaries
    needs: actions-tagger
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install dependencies
        run: npm install

      - name: Build binaries
        run: npm run electron:build --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}